### ISSUE TITLE
Tips BGM

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/meakashi#14] opened 2017-08-27 16:27 UTC
In testing dll, I realize almost of BGM for Tips is not played correctly.
Almost of BGM is set before "DrawScene". I exchange sort, these are played correctly.

Probably "DrawScene" reset BGM.

But I cannot discriminate it is related in vanilla or edited dll or my savedata is collapsed.
Could someone check it?

**Comment by orian34** [comment] 2018-10-14 19:36
BGM are reset because they are following the BGM cleaning without any stop inbetween. Switching works because you have the DrawScene cutting the FadeOutBGM methods from happening at the same time as PlayBGM.

It's a vanilla issue.

Though that's only what I think the issue is.
Considering I fix those, anyone is free to close it if there's nothing more to add.

**Comment by orian34** [comment] 2018-10-14 19:42
Considering just deleting the BGM cleaning without swapping the methods make it work, I'm fairly certain it's related.
Who knows what it could really be though.

**Closed** 2018-10-15 07:47 UTC
