### ISSUE TITLE
Installer - CGAlt did not move from temp?

### ISSUE THREAD

**Issue by nocturne32** [07th-mod/meakashi#3] opened 2017-05-05 23:05 UTC
Hi, thank you for these nice mods for Higurashi.
I was doing it manually before but wanted to try the installer.

Everything went smoothly but it only added the voices. 
Installer downloads the CGAlt to temp folder but it doesn't move it to StreamingAssets/CGAlt. There are still mangagamer's sprites and stuff. 
Tried it 2 times.

**Comment by ItaloKnox** [comment] 2017-05-06 00:41
@DoctorDiablo is correct. If the installer is leaving a CGAlt folder inside the temp folder after finishing the work, then it's a problem. If it's not leaving anything, it is working as intended. We are doing it this way because it stops the game from crashing in any possible cases and it leaves us space to implement the steam sprites after they're completed.

**Comment by nocturne32** [comment] 2017-05-06 07:21
I even looked into the CG folder, but nothing moved from temp. The original CG is intact.
Tried the whole process again but it still did not move from temp to CG.
I really dont know what I am doing wrong.

My path to temp: _common\Higurashi When They Cry Hou - Ch. 5 Meakashi\HigurashiEp05_Data\StreamingAssets\temp_

**Comment by ItaloKnox** [comment] 2017-05-06 18:15
That's odd, can you print the cmd screen while you are installing the patch? Something should happen when it gets to the ``Moving folders`` step. By the way, do you have enough disk space?

I also suggest you to open the file ``install.bat`` that is inside the temp folder and remove this line:
``del .\*.zip > nul``. This will stop the installer from removing the patch files even if the installation fails, so you won't have to redownload it every time it doesn't work.

**Comment by nocturne32** [comment] 2017-05-06 19:31
Just read the EDIT and laughed a bit, it really did delete it anyway... But it's okay now. On 4th try it moved correctly. Don't really know why, I did always the same. 

Just a quick question... There are still the original sprites and BGs in CG folders, is it intentional?
![image](https://cloud.githubusercontent.com/assets/18268621/25775280/f6892610-32a1-11e7-82be-d90abbe635d4.png)
_Side note: I don't really care but changing sprites inside the game doesn't work._

**Comment by ItaloKnox** [comment] 2017-05-06 21:32
Yeah, for some reason in this patch the guy responsible for making the PS3 graphics chose to not remove them. I'll look into it to see if we can remove the unused images.

Also to get the PS3 sprites you need to change your game settings to "Original" instead of "Updated". You probably know that already, so if it's not working I suggest you to clean the ``CompiledUpdateScripts`` folder and run the game again.

**Comment by nocturne32** [comment] 2017-05-06 21:51
Sorry if I wasn't clear. I have the PS3 sprites working nicely. 
I just meant that changing settings to "orignal" or "updated" doesn't change the sprites at all. It keeps the PS3's sprites, which is perfectly fine by me. Just wanted to let you guys know.

**Comment by ItaloKnox** [comment] 2017-05-06 21:55
Ohh, I see. That should be fine, we're still updating the MG sprites to support Meakashi, so that was expected. The game will use the PS3 sprites pretty much most of the time since there's no version of them in the MG sprites.

I'll be closing this issue, then. If you need anything, just reopen it and we'll be here to help. Have fun! 👍

**Closed by ItaloKnox** 2017-05-06 21:55 UTC
