### ISSUE TITLE
Chapter Jump Unlocked

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#34] opened 2018-10-05 17:24 UTC
Even with a fresh install+patch, I will end up with the entire days unlocked and available to jump to, while I never even started reading.

I asked someone else and I got confirmation it happened for them too, so there's definitely a deffective trigger somewhere

**Comment by enumag** [comment] 2018-10-05 18:13
@idealpersona @tellowkrinkle This is on you guys. It's either a DLL issue or a misplaced call in flow.txt. Either way it needs some delving into the DLL code to check which flags unlock that menu.

**Comment by idealpersona** [comment] 2018-10-14 19:08
This may be expected behavior.  Save data is kept separately from the game installation path.  Steam also will synchronize save info unless you configure it not to.  On Windows for Meakashi I believe it's in something like `C:\Users\<you>\AppData\MangaGamer\Higurashi05\`.  I think it's `AppData` but it me slightly different.  It's also a hidden folder, so you'll have to configure Windows Explorer to show hidden files to be able to view it.

**Comment by idealpersona** [comment] 2018-10-14 19:09
Oh is this even before your first pass of Meakashi?  Didn't realize this was 9 days ago.

**Comment by orian34** [comment] 2018-10-14 19:18
Yes, that was before starting, and it was the same for the friend starting at the same time.

**Comment by tellowkrinkle** [comment] 2018-10-15 07:37
Looks like MG [accidentally mapped both `HighestChapter` and `MessageSpeed` to the same variable number](https://github.com/07th-mod/higurashi-assembly/blob/414be73b23cd9001018ca2b6944083fcd48a50ba/Assets.Scripts.Core.Buriko/BurikoMemory.cs#L64-L65), ~~so you can fix it by setting your message speed to the minimum value~~
Which one should we renumber?

**Comment by enumag** [comment] 2018-10-15 09:52
I faintly remember @Doddler tweeting about that. Are you sure it's not fixed in vanilla?

**Comment by orian34** [comment] 2018-10-15 10:41
No idea.
There was this on steam.
![image](https://user-images.githubusercontent.com/12663654/46946271-7e182f80-d077-11e8-8d7b-688ee5a88cc7.png)
So I couldn't tell if it's on us or not.

**Comment by tellowkrinkle** [comment] 2018-10-15 18:43
Ahh actually I just checked the disassembly of one of the more recent `higurashi-dlls` builds and `GMessageSpeed` was changed to `52` there
I guess that change never made it into the disassembled version
Should we set `GHighestChapter` to `28` or `GMessageSpeed` to `52`?

**Comment by enumag** [comment] 2018-10-15 18:50
Ah, use 52 then.

**Closed** 2018-10-15 20:28 UTC

**Comment by tellowkrinkle** [comment] 2018-10-15 20:30
Tested with the [new build](https://07th-mod.com/higurashi_dlls/meakashi/Assembly-CSharp.dll), it seems to work properly now
