### ISSUE TITLE
Meakashi ch 3 issue

### ISSUE THREAD

**Issue by Mikulovers** [07th-mod/meakashi#19] opened 2018-05-16 19:45 UTC
![higubug2](https://user-images.githubusercontent.com/39219285/40140152-6f81858a-5952-11e8-8a65-0301797f51b0.png)

In the shopping scene in ch3 at meakashi Satoshi turns into a white square.

**Comment by Mikulovers** [comment] 2018-05-17 21:03
![bild](https://user-images.githubusercontent.com/39219285/40203714-59f9a48e-5a26-11e8-9ecd-1fdb048ef105.png)
It happens in almost every chapter for certain sprite expressions. If you save and reload it comes up with no sprite until the next expressions is loaded. PS3 and Steam alike.

**Comment by DoctorDiablo** [comment] 2018-05-19 14:04
I found the root cause.  All of the graphics that fail to draw are being done using the ChangeBustshot function.  None of the other chapters used that function, but there are over 100 of these in Meakashi.
`ChangeBustshot( 0, "Me_TohohoA2#", 200, TRUE );`

We need to update these to use ModDrawCharacter() for lipsync to work.  And we also need to rename the sprites, because they're still using the old filenames and missing the folder names in their paths.

@enumag You think you can make a script that can handle this?

**Comment by enumag** [comment] 2018-05-19 15:49
@DoctorDiablo Yeah I'll handle it. I'm guessing I need to find the previous ModDrawCharacter call for the same layer and copy most of the parameters from there, right?

**Comment by enumag** [comment] 2018-05-19 21:47
Should be fixed in [v4.0.1](https://github.com/07th-mod/meakashi/releases/tag/v4.0.1). Note that this release has some missing steam sprites, we're working on that.

Please open a new issue if you still see this or any other problem after applying the 4.0.1 patch.

**Closed by enumag** 2018-05-19 21:47 UTC
